export const SELECT_TRIGGER = "SELECT_TRIGGER";
export const DISSELECT_TRIGGER = "DISSELECT_TRIGGER";

export const OPEN_ACTION_MODAL = "OPEN_ACTION_MODAL";
export const CLOSE_ACTION_MODAL = "CLOSE_ACTION_MODAL";

export const OPEN_VERSION_HISTORY = "OPEN_VERSION_HISTORY";
export const CLOSE_VERSION_HISTORY = "CLOSE_VERSION_HISTORY";

export const OPEN_TRIGGER_SIDEBAR = "OPEN_TRIGGER_SIDEBAR";
export const CLOSE_TRIGGER_SIDEBAR = "CLOSE_TRIGGER_SIDEBAR";

export const OPEN_ACTION_SIDEBAR = "OPEN_ACTION_SIDEBAR";
export const CLOSE_ACTION_SIDEBAR = "CLOSE_ACTION_SIDEBAR";
